FROM golang:latest

WORKDIR /go/src/app

RUN apk add --update &&  apk add git
ADD ./app /go/src/app

ENV GO111MODULE=on
RUN go get -u github.com/cosmtrek/air
RUN go mod download
EXPOSE 8000
CMD ["air"]